=== Naviamold1/common-country-list/list.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Country",
  "description": "List of common countries",
  "type": "array",
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "country": {
        "description": "The name of the country",
        "type": "string"
      },
      "continent": {
        "description": "The continent where the country is located",
        "type": "string"
      },
      "flag": {
        "description": "The flag of the country",
        "type": "string",
        "format": "uri"
      },
      "map": {
        "description": "the map of the country",
        "type": "string",
        "format": "uri"
      },
      "alias": {
        "description": "Other names of the country",
        "type": ["string", "array"],
        "uniqueItems": true
      }
    },
    "required": ["country", "continent", "flag", "map"]
  }
}

=== Naviamold1/common-country-list/list.json
[
  {
    "country": "Afghanistan",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Afghanistan.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Afghanistan.png"
  },
  {
    "country": "Albania",
    "continent": "Europe",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Albania.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Albania.png"
  },
  {
    "country": "Algeria",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Algeria.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Algeria.png"
  },
  {
    "country": "Andorra",
    "continent": "Europe",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Andorra.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Andorra.png"
  },
  {
    "country": "Angola",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Angola.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Angola.png"
  },
  {
    "country": "Antigua and Barbuda",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Antigua%20and%20Barbuda.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Antigua%20and%20Barbuda.png"
  },
  {
    "country": "Argentina",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Argentina.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Argentina.png"
  },
  {
    "country": "Armenia",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Armenia.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Armenia.png"
  },
  {
    "country": "Australia",
    "continent": "Oceania",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Australia.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Australia.png"
  },
  {
    "country": "Austria",
    "continent": "Europe",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Austria.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Austria.png"
  },
  {
    "country": "Azerbaijan",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Azerbaijan.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Azerbaijan.png"
  },
  {
    "country": "Bahamas",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Bahamas.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Bahamas.png"
  },
  {
    "country": "Bahrain",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Bahrain.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Bahrain.png"
  },
  {
    "country": "Bangladesh",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Bangladesh.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Bangladesh.png"
  },
  {
    "country": "Barbados",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Barbados.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Barbados.png"
  },
  {
    "country": "Belarus",
    "continent": "Europe",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Belarus.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Belarus.png"
  },
  {
    "country": "Belgium",
    "continent": "Europe",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Belgium.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Belgium.png"
  },
  {
    "country": "Belize",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Belize.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Belize.png"
  },
  {
    "country": "Benin",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Benin.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Benin.png"
  },
  {
    "country": "Bhutan",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Bhutan.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Bhutan.png"
  },
  {
    "country": "Bolivia",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Bolivia.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Bolivia.png"
  },
  {
    "country": "Bosnia and Herzegovina",
    "continent": "Europe",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Bosnia%20and%20Herzegovina.png",
    "alias": "Bosnia",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Bosnia%20and%20Herzegovina.png"
  },
  {
    "country": "Botswana",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Botswana.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Botswana.png"
  },
  {
    "country": "Brazil",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Brazil.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Brazil.png"
  },
  {
    "country": "Brunei",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Brunei.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Brunei.png"
  },
  {
    "country": "Bulgaria",
    "continent": "Europe",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Bulgaria.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Bulgaria.png"
  },
  {
    "country": "Burkina Faso",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Burkina%20Faso.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Burkina%20Faso.png"
  },
  {
    "country": "Burundi",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Burundi.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Burundi.png"
  },
  {
    "country": "Cambodia",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Cambodia.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Cambodia.png"
  },
  {
    "country": "Cameroon",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Cameroon.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Cameroon.png"
  },
  {
    "country": "Canada",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Canada.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Canada.png"
  },
  {
    "country": "Cape Verde",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Cape%20Verde.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Cape%20Verde.png"
  },
  {
    "country": "Central African Republic",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Central%20African%20Republic.png",
    "alias": "CAR",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Central%20African%20Republic.png"
  },
  {
    "country": "Chad",
    "continent": "Africa",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Chad.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Chad.png"
  },
  {
    "country": "Chile",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Chile.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/Chile.png"
  },
  {
    "country": "China",
    "continent": "Asia",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/China.png",
    "map": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/maps/China.png"
  },
  {
    "country": "Colombia",
    "continent": "Americas",
    "flag": "https://raw.githubusercontent.com/Naviamold1/common-country-list/main/flags/Colombia.png",
